version: '3.8'

services:
  orchestrateur:
    build: ./orchestrateur
    ports:
      - "5050:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CHALLENGE_IMAGE=urgence-au-bloc-challenge:latest
    restart: unless-stopped